slist: utest_slist.o
	g++ utest_slist.o

slist-d: utest_slist.cpp
	g++ -g utest_slist.cpp

utest_slist.o: utest_slist.cpp
	g++ -c utest_slist.cpp

slist-c:
	clang++ utest_slist.cpp

polynomial: utest_polynomial.o
	g++ utest_polynomial.o

polynomial-d: utest_polynomial.cpp
	g++ -g utest_polynomial.cpp

utest_polynomial.o: utest_polynomial.cpp
	g++ -c utest_polynomial.cpp

polynomial-c:
	clang++ utest_polynomial.cpp

