slist: slist.o main_slist.o
	g++ slist.o main_slist.o

slist-d: slist.cpp main_slist.cpp
	g++ -g slist.cpp main_slist.cpp

slist.o: slist.cpp
	g++ -c slist.cpp
main_slist.o: main_slist.cpp
	g++ -c main_slist.cpp
